/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface KeyCount {
  key: string
  count: number
}
export declare function collectI18NKeys(sources: Array<string>): Array<KeyCount>
